In [1]:
import cv2
import numpy as np

In [2]:
face_classifier =cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [7]:
def face_extractor(img):
    faces= face_classifier.detectMultiScale(img,1.3,5)
    
    if faces is ():
        return None
    
    for(x,y,w,h) in faces:
        x=x-10
        y=y-10
        cropped_face = img[y:y+h+50, x:x+w+50]
    return cropped_face

# Initialised Webcam
cap =cv2.VideoCapture(0)
count = 0

# Collect 50 samples of face
while True:
    print("True")
    ret, frame =cap.read()
    
    if face_extractor(frame) is not None:
        count +=1
        face =cv2.resize(face_extractor(frame),(400,400))
        print(face)
        file_name_path ='Moiz/' + str(count) + '.jpg'
        
        print(file_name_path)
        z=cv2.imwrite(file_name_path,face)
        print(z)
        
        cv2.putText(face,str(count),(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
        cv2.imshow("Face Cropper",face)
    else:
        print("Face Not found",str(count))
        pass
    
    if cv2.waitKey(1) == 13 or count == 50 :
        break
        
cap.release()
cv2.destroyAllWindows()

print("Collecting Samples Complete")

True
[[[152 165 150]
  [151 163 149]
  [150 162 148]
  ...
  [161 177 178]
  [160 176 177]
  [160 176 176]]

 [[152 165 149]
  [151 163 149]
  [150 162 148]
  ...
  [161 177 179]
  [161 176 178]
  [160 176 177]]

 [[151 164 149]
  [150 163 148]
  [150 162 148]
  ...
  [162 177 181]
  [161 176 180]
  [161 176 179]]

 ...

 [[162 111 102]
  [160 109 100]
  [157 107  98]
  ...
  [ 80  40  37]
  [ 80  40  37]
  [ 80  40  37]]

 [[164 110 101]
  [162 109 100]
  [159 106  98]
  ...
  [ 80  40  37]
  [ 80  40  37]
  [ 81  40  37]]

 [[165 110 101]
  [163 108 100]
  [161 106  98]
  ...
  [ 80  40  37]
  [ 81  41  37]
  [ 81  41  38]]]
Moiz/1.jpg
True
True
[[[148 150 139]
  [146 149 137]
  [144 146 135]
  ...
  [197 208 191]
  [198 208 191]
  [199 209 192]]

 [[148 150 138]
  [146 148 136]
  [143 145 133]
  ...
  [199 208 192]
  [199 208 192]
  [200 208 193]]

 [[149 150 136]
  [146 147 133]
  [143 144 130]
  ...
  [201 208 194]
  [201 208 194]
  [201 208 194]]

 ...

 [[156 107 100]
  [156 108

  [156 139 115]]]
Moiz/13.jpg
True
True
Face Not found 13
True
[[[139 153 163]
  [139 153 163]
  [139 153 163]
  ...
  [253 255 253]
  [253 255 253]
  [253 255 253]]

 [[139 153 163]
  [139 153 163]
  [139 153 163]
  ...
  [253 255 253]
  [253 255 253]
  [253 255 253]]

 [[139 153 163]
  [139 153 163]
  [139 153 163]
  ...
  [253 255 253]
  [253 255 253]
  [253 255 253]]

 ...

 [[119 128 128]
  [119 128 128]
  [119 128 128]
  ...
  [152 133 119]
  [154 134 122]
  [154 134 122]]

 [[121 130 129]
  [121 130 129]
  [120 130 129]
  ...
  [152 133 119]
  [154 134 122]
  [154 134 122]]

 [[121 130 129]
  [121 130 129]
  [120 130 129]
  ...
  [152 133 119]
  [154 134 122]
  [154 134 122]]]
Moiz/14.jpg
True
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
Face Not found 14
True
[[[138 154 164]
  [138 154 164]


  [ 70  51  46]]]
Moiz/27.jpg
True
True
[[[ 74 102 120]
  [ 74 102 120]
  [ 74 102 120]
  ...
  [149 162 166]
  [147 160 163]
  [146 159 162]]

 [[ 72 101 120]
  [ 72 101 120]
  [ 73 101 120]
  ...
  [144 158 162]
  [142 156 160]
  [141 155 158]]

 [[ 68  99 120]
  [ 68  99 120]
  [ 70 100 121]
  ...
  [133 152 154]
  [131 150 152]
  [130 149 152]]

 ...

 [[104  79  62]
  [104  79  62]
  [104  78  61]
  ...
  [ 73  48  44]
  [ 73  48  44]
  [ 73  48  44]]

 [[105  79  63]
  [105  79  63]
  [105  79  63]
  ...
  [ 72  48  44]
  [ 72  48  44]
  [ 72  48  44]]

 [[105  79  64]
  [105  79  64]
  [105  79  64]
  ...
  [ 72  48  44]
  [ 72  48  44]
  [ 72  48  44]]]
Moiz/28.jpg
True
True
[[[ 92  96 118]
  [ 93  96 117]
  [ 94  95 114]
  ...
  [125 133 128]
  [123 131 125]
  [122 130 124]]

 [[ 89  95 117]
  [ 90  95 116]
  [ 92  95 114]
  ...
  [122 128 123]
  [121 127 122]
  [121 127 121]]

 [[ 84  94 116]
  [ 85  95 115]
  [ 87  95 114]
  ...
  [117 120 115]
  [118 121 116]
  [119 122 117

  [ 77  38  37]]]
Moiz/40.jpg
True
True
[[[ 72  92 125]
  [ 71  94 127]
  [ 70  99 131]
  ...
  [180 196 186]
  [179 195 185]
  [179 195 185]]

 [[ 74  94 127]
  [ 73  96 129]
  [ 71 100 131]
  ...
  [180 196 184]
  [179 196 183]
  [179 195 183]]

 [[ 78  99 132]
  [ 75 100 131]
  [ 71 100 131]
  ...
  [179 197 181]
  [178 196 180]
  [178 196 180]]

 ...

 [[124  68  70]
  [122  67  67]
  [120  64  63]
  ...
  [ 66  47  38]
  [ 66  47  38]
  [ 66  47  38]]

 [[122  70  69]
  [122  69  67]
  [121  67  62]
  ...
  [ 67  47  38]
  [ 67  46  37]
  [ 67  46  37]]

 [[121  71  69]
  [121  70  66]
  [121  69  61]
  ...
  [ 68  47  37]
  [ 67  46  36]
  [ 67  46  36]]]
Moiz/41.jpg
True
True
[[[ 59  73 113]
  [ 59  73 113]
  [ 59  73 113]
  ...
  [184 196 181]
  [184 196 181]
  [184 196 181]]

 [[ 58  72 113]
  [ 58  72 112]
  [ 58  72 112]
  ...
  [185 196 181]
  [185 196 181]
  [185 196 181]]

 [[ 56  71 112]
  [ 56  70 112]
  [ 55  70 112]
  ...
  [187 196 181]
  [187 196 181]
  [187 196 181